-- רשימת ערים משותפת, במקום שלוש רשימות מוקשחות בקוד הלקוח.
-- אידמפוטנטית: אפשר להריץ שוב בלי נזק.
CREATE TABLE IF NOT EXISTS "City" (
  "id"        TEXT PRIMARY KEY,
  "name"      TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "isPreset"  BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "City_name_key" ON "City"("name");

-- הזרעת הרשימה שהייתה עד היום בקוד (איחוד שלוש הרשימות).
-- ON CONFLICT DO NOTHING כדי שהרצה חוזרת לא תיצור כפילויות ולא תדרוס
-- ערים שעובדים הוסיפו בינתיים.
INSERT INTO "City" ("id", "name", "sortOrder", "isPreset", "createdAt") VALUES
  (gen_random_uuid()::text, 'אום אל-פחם', 1, true, NOW()),
  (gen_random_uuid()::text, 'אופקים', 2, true, NOW()),
  (gen_random_uuid()::text, 'אור יהודה', 3, true, NOW()),
  (gen_random_uuid()::text, 'אור עקיבא', 4, true, NOW()),
  (gen_random_uuid()::text, 'אילת', 5, true, NOW()),
  (gen_random_uuid()::text, 'אלעד', 6, true, NOW()),
  (gen_random_uuid()::text, 'אריאל', 7, true, NOW()),
  (gen_random_uuid()::text, 'אשדוד', 8, true, NOW()),
  (gen_random_uuid()::text, 'אשקלון', 9, true, NOW()),
  (gen_random_uuid()::text, 'באר יעקב', 10, true, NOW()),
  (gen_random_uuid()::text, 'באר שבע', 11, true, NOW()),
  (gen_random_uuid()::text, 'בית שאן', 12, true, NOW()),
  (gen_random_uuid()::text, 'בית שמש', 13, true, NOW()),
  (gen_random_uuid()::text, 'ביתר עילית', 14, true, NOW()),
  (gen_random_uuid()::text, 'בני ברק', 15, true, NOW()),
  (gen_random_uuid()::text, 'בת ים', 16, true, NOW()),
  (gen_random_uuid()::text, 'גבעת אדה', 17, true, NOW()),
  (gen_random_uuid()::text, 'גבעת שמואל', 18, true, NOW()),
  (gen_random_uuid()::text, 'גבעתיים', 19, true, NOW()),
  (gen_random_uuid()::text, 'גדרה', 20, true, NOW()),
  (gen_random_uuid()::text, 'גן יבנה', 21, true, NOW()),
  (gen_random_uuid()::text, 'גני תקווה', 22, true, NOW()),
  (gen_random_uuid()::text, 'דימונה', 23, true, NOW()),
  (gen_random_uuid()::text, 'הוד השרון', 24, true, NOW()),
  (gen_random_uuid()::text, 'הרצליה', 25, true, NOW()),
  (gen_random_uuid()::text, 'זכרון יעקב', 26, true, NOW()),
  (gen_random_uuid()::text, 'חדרה', 27, true, NOW()),
  (gen_random_uuid()::text, 'חולון', 28, true, NOW()),
  (gen_random_uuid()::text, 'חיפה', 29, true, NOW()),
  (gen_random_uuid()::text, 'טבריה', 30, true, NOW()),
  (gen_random_uuid()::text, 'טייבה', 31, true, NOW()),
  (gen_random_uuid()::text, 'טירה', 32, true, NOW()),
  (gen_random_uuid()::text, 'טירת כרמל', 33, true, NOW()),
  (gen_random_uuid()::text, 'טמרה', 34, true, NOW()),
  (gen_random_uuid()::text, 'יבנה', 35, true, NOW()),
  (gen_random_uuid()::text, 'יהוד-מונוסון', 36, true, NOW()),
  (gen_random_uuid()::text, 'יקנעם', 37, true, NOW()),
  (gen_random_uuid()::text, 'יקנעם עילית', 38, true, NOW()),
  (gen_random_uuid()::text, 'ירוחם', 39, true, NOW()),
  (gen_random_uuid()::text, 'ירושלים', 40, true, NOW()),
  (gen_random_uuid()::text, 'כוכב יאיר', 41, true, NOW()),
  (gen_random_uuid()::text, 'כפר ורדים', 42, true, NOW()),
  (gen_random_uuid()::text, 'כפר יונה', 43, true, NOW()),
  (gen_random_uuid()::text, 'כפר יסיף', 44, true, NOW()),
  (gen_random_uuid()::text, 'כפר סבא', 45, true, NOW()),
  (gen_random_uuid()::text, 'כפר קאסם', 46, true, NOW()),
  (gen_random_uuid()::text, 'כפר קרע', 47, true, NOW()),
  (gen_random_uuid()::text, 'כרמיאל', 48, true, NOW()),
  (gen_random_uuid()::text, 'להבים', 49, true, NOW()),
  (gen_random_uuid()::text, 'לוד', 50, true, NOW()),
  (gen_random_uuid()::text, 'מגדל העמק', 51, true, NOW()),
  (gen_random_uuid()::text, 'מודיעין עילית', 52, true, NOW()),
  (gen_random_uuid()::text, 'מודיעין-מכבים-רעות', 53, true, NOW()),
  (gen_random_uuid()::text, 'מזכרת בתיה', 54, true, NOW()),
  (gen_random_uuid()::text, 'מיתר', 55, true, NOW()),
  (gen_random_uuid()::text, 'מעלה אדומים', 56, true, NOW()),
  (gen_random_uuid()::text, 'מעלות-תרשיחא', 57, true, NOW()),
  (gen_random_uuid()::text, 'נהריה', 58, true, NOW()),
  (gen_random_uuid()::text, 'נוף הגליל', 59, true, NOW()),
  (gen_random_uuid()::text, 'נס ציונה', 60, true, NOW()),
  (gen_random_uuid()::text, 'נצרת', 61, true, NOW()),
  (gen_random_uuid()::text, 'נשר', 62, true, NOW()),
  (gen_random_uuid()::text, 'נתיבות', 63, true, NOW()),
  (gen_random_uuid()::text, 'נתניה', 64, true, NOW()),
  (gen_random_uuid()::text, 'עומר', 65, true, NOW()),
  (gen_random_uuid()::text, 'עכו', 66, true, NOW()),
  (gen_random_uuid()::text, 'עפולה', 67, true, NOW()),
  (gen_random_uuid()::text, 'ערד', 68, true, NOW()),
  (gen_random_uuid()::text, 'פרדס חנה-כרכור', 69, true, NOW()),
  (gen_random_uuid()::text, 'פתח תקווה', 70, true, NOW()),
  (gen_random_uuid()::text, 'צפת', 71, true, NOW()),
  (gen_random_uuid()::text, 'קלנסוה', 72, true, NOW()),
  (gen_random_uuid()::text, 'קלנסווה', 73, true, NOW()),
  (gen_random_uuid()::text, 'קציר-חריש', 74, true, NOW()),
  (gen_random_uuid()::text, 'קצרין', 75, true, NOW()),
  (gen_random_uuid()::text, 'קריית אונו', 76, true, NOW()),
  (gen_random_uuid()::text, 'קריית אתא', 77, true, NOW()),
  (gen_random_uuid()::text, 'קריית ביאליק', 78, true, NOW()),
  (gen_random_uuid()::text, 'קריית גת', 79, true, NOW()),
  (gen_random_uuid()::text, 'קריית ים', 80, true, NOW()),
  (gen_random_uuid()::text, 'קריית מוצקין', 81, true, NOW()),
  (gen_random_uuid()::text, 'קריית מלאכי', 82, true, NOW()),
  (gen_random_uuid()::text, 'קריית שמונה', 83, true, NOW()),
  (gen_random_uuid()::text, 'קרית אונו', 84, true, NOW()),
  (gen_random_uuid()::text, 'קרית אתא', 85, true, NOW()),
  (gen_random_uuid()::text, 'קרית ביאליק', 86, true, NOW()),
  (gen_random_uuid()::text, 'קרית גת', 87, true, NOW()),
  (gen_random_uuid()::text, 'קרית טבעון', 88, true, NOW()),
  (gen_random_uuid()::text, 'קרית מוצקין', 89, true, NOW()),
  (gen_random_uuid()::text, 'קרית מלאכי', 90, true, NOW()),
  (gen_random_uuid()::text, 'קרית שמונה', 91, true, NOW()),
  (gen_random_uuid()::text, 'ראמה', 92, true, NOW()),
  (gen_random_uuid()::text, 'ראש העין', 93, true, NOW()),
  (gen_random_uuid()::text, 'ראשון לציון', 94, true, NOW()),
  (gen_random_uuid()::text, 'רהט', 95, true, NOW()),
  (gen_random_uuid()::text, 'רחובות', 96, true, NOW()),
  (gen_random_uuid()::text, 'רמלה', 97, true, NOW()),
  (gen_random_uuid()::text, 'רמת גן', 98, true, NOW()),
  (gen_random_uuid()::text, 'רמת השרון', 99, true, NOW()),
  (gen_random_uuid()::text, 'רעננה', 100, true, NOW()),
  (gen_random_uuid()::text, 'שגב-שלום', 101, true, NOW()),
  (gen_random_uuid()::text, 'שדרות', 102, true, NOW()),
  (gen_random_uuid()::text, 'שהם', 103, true, NOW()),
  (gen_random_uuid()::text, 'שלומי', 104, true, NOW()),
  (gen_random_uuid()::text, 'שפרעם', 105, true, NOW()),
  (gen_random_uuid()::text, 'תל אביב-יפו', 106, true, NOW())
ON CONFLICT ("name") DO NOTHING;
