-- Seed: insert "בדיקת קול הולם אקוסטיקה" merge template
-- This is a data-only migration — no schema changes.

INSERT INTO "QuoteTemplate" (
  "id", "name", "serviceType", "isActive",
  "introHtml", "bodyHtml", "closingHtml", "termsHtml",
  "variablesHelp", "defaultLineItems",
  "createdAt", "updatedAt"
) VALUES (
  gen_random_uuid(),
  'בדיקת קול הולם אקוסטיקה',
  'אקוסטיקה / רעש',
  true,
  -- introHtml
  E'<div dir="rtl" style="font-family:''David'',''Arial'',sans-serif;font-size:13px;line-height:1.7;">\n  <h2 style="text-align:center;margin-bottom:4px;">סקר חוזה מס'': {{quoteNumber}}</h2>\n\n  <p><strong>לכבוד</strong><br/>{{customerName}}</p>\n  <p>נייד: {{customerPhone}}<br/>מייל: {{customerEmail}}</p>\n\n  <p><strong>הנדון:</strong> הצעת מחיר לבדיקת עמידה בתקן ישראלי ת"י 1004 חלק 1 אקוסטיקת מבנים – מדד הקול ההולם לרבות מעברי איגוף L''n,w</p>\n\n  <p>שלום רב,</p>\n\n  <p>גלית – החברה לאיכות הסביבה בע״מ היא חברה ותיקה ומובילה בתחומה, בעלת ניסיון של כ-30 שנה בביצוע בדיקות סביבתיות, מדידות רעש וייעוץ אקוסטי.</p>\n\n  <p>החברה מפעילה מעבדה מוסמכת לבדיקות רעש ואקוסטיקה לפי תקן ISO/IEC 17025, בהסמכת הרשות הלאומית להסמכת מעבדות, וכן מוכרת ע״י מכון התקנים הישראלי בתקן ISO 9001 לניהול איכות ובתקן ISO 14001 לניהול סביבתי.</p>\n\n  <p>החברה משרתת מגוון רחב של לקוחות – מוסדות ציבור, רשויות, גופים ממשלתיים, חברות תשתית ולקוחות פרטיים – תוך שמירה על סטנדרטים מקצועיים מהגבוהים בענף, ציוד מדידה מתקדם, צוות בודקים מוסמכים ונהלי איכות מוקפדים.</p>\n</div>',
  -- bodyHtml
  E'<div dir="rtl" style="font-family:''David'',''Arial'',sans-serif;font-size:13px;line-height:1.7;">\n  <p>בהמשך לפנייתך, אנו מתכבדים להציע מתווה לביצוע בדיקת עמידה בתקן ישראלי ת"י 1004 חלק 1 אקוסטיקת מבנים – מדד הקול ההולם לרבות מעברי איגוף L''n,w ב{{customerAddress}}.</p>\n\n  <h3>מטרה</h3>\n  <p>בדיקת רמת הבידוד האקוסטי הנדרש לקול הולם עבור צמד תקרה רצפה בין דירות צמודות.</p>\n\n  <h3>תיאור המקרה</h3>\n  <p>בדירה תחתונה נשמעים נקישות, הליכה והזזת רהיטים של השכנים.</p>\n\n  <h3>ביצוע בדיקות ע"פ המפרט הבא:</h3>\n  <p>הגעת בודק מוסמך ממעבדה לאתר הנבדק.</p>\n  <ul>\n    <li>ביצוע מדידות באופן הבא: פטישיה תקנית מוצבת בחדר מקור הרעש במספר נקודות בוחן. מפלסי לחץ הקול נמדדים בחדר בדירה סמוכה מעבר לקיר/צמד תקרה רצפה נבדק.</li>\n    <li>מהלך המדידה מבוצע בהתאם לתקן ישראלי ת"י 1034 חלק 7, אקוסטיקה: מדידת בידוד קול בבניינים ובאלמנטים בבניין – מדידות באתר של בידוד קול הולם ברצפות.</li>\n    <li>חישוב זמן ההדהוד בחדר הקליטה מבוצע בהתאם ל ISO 3382-2. אפקט ההדהוד מושג כנדרש על ידי רמקול רב כיווני.</li>\n    <li>המדידה מבוצעת בלפחות 3 מיקומים אקראיים בחדר הקליטה כאשר בכל נקודה מבוצעות 2 מדידות.</li>\n    <li>תיקון לרעש הרקע מבוצע בהתאם לנדרש ב ת"י 1034 חלק 7.</li>\n    <li>הערכת שיעור הבידוד האקוסטי, מבוצע בהתאם לתקן ישראלי ת"י 985, חלק 2: "אקוסטיקה – הערכת שיעור הבידוד האקוסטי בבניינים והבידוד האקוסטי של אלמנטים בבניין – בידוד מפני קול הולם". מ- מרץ 2014.</li>\n    <li>הערכים הנמדדים ומחושבים נבחנים ביחס לתקן ישראלי ת"י 1004-1: בידוד אקוסטי בבתי מגורים: קירות ותקרות (רצפות) בין דירות – דרישות ושיטות חישוב ובו הערכים הנדרשים לעמידה בתקן.</li>\n    <li>כלל שיטות העבודה ואופן ביצועה מבוססים על נהלי שיטות הבדיקה הישימים של המעבדה המוסמכת.</li>\n    <li>דו"ח סיכום המדידה הינו מסמך מעבדתי המהווה ראיה משפטית.</li>\n    <li>דו"ח סיכום המדידה יועבר בדוא"ל למזמין עד 14 ימי עבודה, כפוף לכוח עליון ובלתי צפוי מראש.</li>\n    <li>תיאום המדידה יבוצע תוך 7 ימי עבודה מאישור ההזמנה.</li>\n    <li>מזמין העבודה מתחייב לעמוד בתנאי התשלום המפורטים בסקר חוזה זה.</li>\n  </ul>\n\n  <h3>הערות כלליות</h3>\n  <ul>\n    <li>נדרש תיאום וזמינות לביצוע המדידה במבנה הנבדק ובחלל הגובל אליו מיוחסת המדידה (כגון דירה סמוכה, משרד צמוד או חדר אחר).</li>\n    <li>יש להקצות משך זמן של עד 120 דקות לצורך ביצוע המדידה בחללים הנבדקים, בהתאם לאופי המבנה.</li>\n    <li>יש לוודא היעדר שטיח/פרקט המכסה את פני רצפת צמד תקרה/רצפה הנבדק.</li>\n    <li>במהלך המדידה מיוצר לחץ קול בעוצמה גבוהה בחדר קולט הרעש. רעש גבוה זה ישמע בכלל חלל הדירה למשך עד כ-2 דקות במצטבר.</li>\n    <li>נדרש שקט יחסי באתר בעת המדידה – רעשי רקע חריגים (למשל: אתר בנייה, כלים חשמליים) עלולים להשפיע על תוצאות המדידה ולפגוע באמינותן.</li>\n    <li>תוצאות התאמה למפרט אינה מתחשבת באי בערך אי וודאות של השיטה.</li>\n    <li>במקרה של בדיקה תחת הסמכה, סמליל הרשות להסמכת מעבדות יופיע באופן אוטומטי על גבי הדוח. אם הלקוח מעוניין להסיר את הסמליל, עליו לפנות למעבדה טרם הפקת הדוח.</li>\n  </ul>\n\n  <h3>3. שכר טרחה</h3>\n  <p>ראה נספח מס'' 1.</p>\n\n  <p>אשמח לענות על כל שאלה בנושא.</p>\n\n  <p>בברכה,<br/>גלית – החברה לאיכות הסביבה בע״מ</p>\n</div>',
  -- closingHtml
  E'<div dir="rtl" style="font-family:''David'',''Arial'',sans-serif;font-size:13px;line-height:1.7;">\n  <h3>מתן חוות דעת מומחה בנושא בדיקת רמת הבידוד האקוסטי הנדרש לקול הולם</h3>\n\n  <h3>נספח מס 1: שכר טרחה והסדרי עבודה</h3>\n\n  <p>מחיר ביצוע תכולת העבודה ע"פ סעיף מס'' 1 בהצעה הינו:</p>\n\n  {{itemsTable}}\n\n  <table dir="rtl" border="1" cellpadding="8" style="border-collapse:collapse;width:100%;max-width:720px;margin-top:8px;">\n    <tr>\n      <td style="border:1px solid #bbb;padding:4px 8px;font-weight:bold;">% הנחה</td>\n      <td style="border:1px solid #bbb;padding:4px 8px;">{{discountPercent}}%</td>\n    </tr>\n    <tr>\n      <td style="border:1px solid #bbb;padding:4px 8px;font-weight:bold;">סה"כ לאחר הנחה</td>\n      <td style="border:1px solid #bbb;padding:4px 8px;">{{subtotalAfterDiscount}}</td>\n    </tr>\n    <tr>\n      <td style="border:1px solid #bbb;padding:4px 8px;font-weight:bold;">מע"מ 18%</td>\n      <td style="border:1px solid #bbb;padding:4px 8px;">{{vat}}</td>\n    </tr>\n    <tr>\n      <td style="border:1px solid #bbb;padding:4px 8px;font-weight:bold;">סה"כ לתשלום</td>\n      <td style="border:1px solid #bbb;padding:4px 8px;font-weight:bold;">{{total}}</td>\n    </tr>\n  </table>\n\n  <p style="margin-top:12px;">למען הסר ספק: במידה ונתבקש לבצע עבודות נוספות אשר אינן כלולות במסגרת הצעת עבודה זו נחייבכם בהתאם לשעות העבודה שנשקיע בפועל לאחר אישורכם לביצוען.</p>\n\n  <p>תוצאות הבדיקות הינן אובייקטיביות, ומתבססות אך ורק על הנתונים שנמדדו בפועל ובהתאם לתקנים הרלוונטיים. אין באפשרות המזמין או הגורם המממן להשפיע על תוצאות אלו או לשנותן.</p>\n\n  <p>לוחות זמנים: ייקבעו בהתאם לקבלת הזמנת העבודה.</p>\n\n  <p>תנאי תשלום: {{paymentTerms}}</p>\n\n  <p>תוקף ההצעה: {{validityDate}}</p>\n\n  <p>תאריך הצעה: {{quoteDate}}</p>\n\n  <p>אישור ההצעה: נא לשלוח את ההצעה חתומה לפקס 09-7724446 ואנו נחזור לתאם הגעה בהקדם.</p>\n\n  <p>הנני מאשר את ההצעה על כל סעיפיה.</p>\n\n  <table dir="rtl" border="1" cellpadding="8" style="border-collapse:collapse;width:100%;max-width:720px;margin-top:12px;">\n    <thead>\n      <tr>\n        <th style="border:1px solid #bbb;padding:4px 8px;background:#f5f5f5;">שם מלא של מאשר ההצעה</th>\n        <th style="border:1px solid #bbb;padding:4px 8px;background:#f5f5f5;">חתימה</th>\n        <th style="border:1px solid #bbb;padding:4px 8px;background:#f5f5f5;">חותמת</th>\n      </tr>\n    </thead>\n    <tbody>\n      <tr>\n        <td style="border:1px solid #bbb;padding:8px;min-height:40px;">{{approverName}}</td>\n        <td style="border:1px solid #bbb;padding:8px;min-height:40px;">&nbsp;</td>\n        <td style="border:1px solid #bbb;padding:8px;min-height:40px;">&nbsp;</td>\n      </tr>\n    </tbody>\n  </table>\n\n  <p style="margin-top:12px;">לתיאום הגעה, נא לחתום ולשלוח לפקס 09-7724446. תודה.</p>\n\n  <p><strong>נספח א'': תעודת הסמכה של הרשות להסמכת מעבדות</strong></p>\n  <p><strong>נספח ב'': תעודות ISO</strong></p>\n</div>',
  -- termsHtml (empty — terms embedded in closingHtml)
  '',
  -- variablesHelp
  E'{{quoteNumber}} — מספר סקר חוזה\n{{customerName}} — שם לקוח\n{{customerPhone}} — נייד\n{{customerEmail}} — מייל\n{{customerAddress}} — כתובת / מיקום הבדיקה\n{{quoteDate}} — תאריך הצעה\n{{itemsTable}} — טבלת פריטים (כולל מק"ט, תיאור, כמות, מחיר, הנחה, סה"כ)\n{{discountPercent}} — אחוז הנחה כללי\n{{subtotalAfterDiscount}} — סה"כ לאחר הנחה\n{{vat}} — מע"מ 18%\n{{total}} — סה"כ לתשלום\n{{paymentTerms}} — תנאי תשלום\n{{validityDate}} — תוקף ההצעה\n{{approverName}} — שם מלא של מאשר ההצעה',
  -- defaultLineItems
  '[{"name":"בדיקת קול הולם – מדד L''n,w","quantity":1,"unitPrice":2000}]'::jsonb,
  NOW(),
  NOW()
)
ON CONFLICT DO NOTHING;
